# 02 — Reproducible preprocessing and feature engineering

## Contract

This notebook builds versioned outputs from the four raw CSVs, `configs/preprocessing_v2.json`,
and the explicitly preserved `configs/frozen_user_split_v1.csv`. It does not read legacy
`final_data` artifacts. The complete previous notebook is backed up in
`archive/02_data_preprocessing_and_feature_engineering_pre_v2.ipynb`.

**Identity:** `user_key` is the only identity/join key. Numeric IDs are metadata only;
string loading does not recover precision already lost upstream.

**Population:** retain users missing temporal, text, or graph modalities. Exclude only
nonbinary annotations from the binary task, missing identities from canonical account
construction, and the explicitly recorded corrupted account. Unexpected identity conflicts
stop the run rather than silently choosing records.

**Missingness:** canonical tables preserve NaNs. Temporal values are never statistically
imputed. Model matrices may contain zero placeholders after scaling, accompanied by observed
feature masks and modality masks. A missing temporal branch must be gated out by later models.

**Preservation:** outputs go to `final_data/versions/preprocessing_v2_<fingerprint>/`. A matching
rerun is idempotent; different existing content is never overwritten. Legacy artifacts and
models remain available. No model training occurs here.

## 1. Configuration and reproducibility

One explicit policy fixes the historical 40-feature order, feature groups, transforms,
source precedence, text rules, exclusions, and graph access. Review `definition_changes`
below: unknown inputs now remain missing in derived features; invalid negative measurements
are flagged instead of clipped. These changes are intentional and versioned.

Frozen assignments are copied once into configuration and validated against current raw
annotations. No random re-split occurs in this notebook. Runtime versions and all input hashes
are captured in the output manifest. Reusable implementations live in `src/preprocessing.py`.

In [1]:
from pathlib import Path
import sys
from IPython.display import display

PROJECT_ROOT = next((p for p in [Path.cwd().resolve(), *Path.cwd().resolve().parents]
                     if (p / 'configs/preprocessing_v2.json').is_file()), None)
if PROJECT_ROOT is None:
    raise RuntimeError('Run from the repository root or analysis directory.')
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
from src.preprocessing import PreprocessingRun, verify_export

run = PreprocessingRun(PROJECT_ROOT)
display(run.config['groups'])
display(run.config['definition_changes'])
display(run.config['missingness'])

{'profile': ['followers_count',
  'friends_count',
  'favourites_count',
  'listed_count',
  'media_count',
  'statuses_count',
  'user_age',
  'follower_growth_rate',
  'friends_growth_rate',
  'default_profile',
  'default_profile_image',
  'has_custom_timelines',
  'possibly_sensitive',
  'hashtag_in_description',
  'numbers_in_description',
  'description_length',
  'followers_friend_ratio',
  'num_digits_in_name',
  'num_digits_in_username',
  'url_in_description'],
 'temporal': ['time_between_tweets',
  'tweet_frequency',
  'min_tweets_per_hour',
  'min_tweets_per_day',
  'max_tweets_per_hour',
  'max_tweets_per_day',
  'max_occurence_of_same_gap'],
 'behavioral': ['no_type_tweet',
  'no_type_retweet_with_comment',
  'no_type_reply',
  'mean_no_media_per_tweet',
  'mean_no_words',
  'no_languages',
  'mean_no_hashtags',
  'mean_favourites_per_tweet',
  'unique_mention_rate_per_tweet',
  'mean_user_mentions_per_tweet',
  'retweet_as_tweet_rate',
  'no_retweet_tweets',
  'mean_retweets_per_tweet']}

{'followers_friend_ratio': 'Preserve followers/friends when friends>0 and followers when friends==0. Missing/invalid denominator now remains missing instead of falling through to followers.',
 'description_length': 'Preserve raw character count for observed descriptions, including observed empty strings. Missing raw description now remains missing instead of becoming length zero.',
 'name_digit_counts': 'Preserve Unicode isdigit counts on observed strings; missing source now remains missing instead of zero.',
 'url_in_description': 'Same regex; missing raw description now remains missing instead of 0.',
 'invalid_negative_values': 'Mark invalid and report, rather than clip.',
 'feature_selection': 'Fixed historical 40-feature design, not a new full-data selection procedure. Historical test reuse remains a limitation.'}

{'temporal': 'No estimated temporal values. Canonical NaNs retained; fit each scaler on finite observed training values; zero placeholder only after scaling with per-feature observed masks. Entire absent temporal branch must be gated out.',
 'non_temporal_numeric': 'Training median before log1p and robust scaling; retain per-feature observed masks.',
 'binary': 'Training most-frequent observed value; ties choose 0; retain observed masks.',
 'no_training_observations': 'Disable feature, zero numerical placeholder, feature_enabled=0; preserve schema.',
 'invalid_values': 'Report and mark negative nonnegative measurements, infinities, and parse failures missing; never silently clip.'}

## 2. Raw source loading and identity inventory

Only raw files are loaded. The 19K collection is an overlapping account source, not a purely
unlabeled dataset. Repeated authors in tweets and repeated graph observations are expected;
canonical account keys must be unique. Numeric IDs never resolve or override a user key.

In [2]:
display(run.load_sources())
display(run.input_hashes)
print('Versioned output directory:', run.output_dir)

      source   rows  unique_keys  missing_key_rows  repeated_key_rows
0  annotated   1103         1103                 0                  0
1   accounts  19510        19435                75                  0
2     tweets  75913         1099                 0              75644
3      graph   3453         3359                10                161

{'data/1000user_sheet - 1k_users.csv': 'ba8e7a4564f798f0d7f2270df1100926ec597d5b73756dde034cc5eb32df504c',
 'data/all_users_new - 19k.csv': 'f578fb8c2276008f735845f712dcde3cceba7f3e33a398b8bccd2963941b18b7',
 'data/1000user_sheet - tweets_meta_data.csv': '6553cc22fa714866bbf59da281698fafc5db221e83765d8e5b6ab2d7b8c0cd55',
 'data/all_users_new - follower_following.csv': 'de73cc8da82417757e03c3b139fe08a8e966546237f840eb714d6ab72d5f3389',
 'configs\\preprocessing_v2.json': '496c7e45cc71e92f83db4021539c068c958026d85f42ded8bead80ee84b1f14e',
 'configs/frozen_user_split_v1.csv': '7da9a7e40a2043352739ff5f739ee67c9f2fd4080ba8875059631230dd97f7b4',
 'src/preprocessing.py': '0f0f573528bb00e6e8ccac8e5a7c195c63fb69947a475e155d922f4ab41bc565'}

Versioned output directory: C:\Users\p.vazifeh\Desktop\University\Project\Bot Detection Implementation\final_data\versions\preprocessing_v2_e861084d1a722a21

## 3. Canonical users, feature validity, and source provenance

Retain the existing source rule: account features come from raw 19K records and gold labels
come only from the annotated source. Missing 19K values are not backfilled from annotations.
All annotated categories are excluded from the true-unlabeled pool. Cross-source comparisons
report disagreements without changing source precedence based on labels.

Feature groups are disjoint. Provided temporal/behavioral aggregates retain their source
values, but upstream formula and observation-window provenance remains unresolved. Numeric
coercion, infinities, invalid negatives, and unknown booleans are reported before mask creation.
No imputer or scaler is fitted in this section.

In [3]:
display(run.build_users())
display(run.reports['value_validation'])
display(run.reports['source_comparison'])

       population  users
0  binary_labeled    959
1  true_unlabeled  18331
2   all_annotated   1103

,source,feature,rows,raw_missing,negative,infinite,nonnull_invalid,valid_observed
0,canonical_19k,followers_count,19434,4,0,0,0,19430
1,canonical_19k,friends_count,19434,4,0,0,0,19430
2,canonical_19k,favourites_count,19434,0,0,0,0,19434
3,canonical_19k,listed_count,19434,0,0,0,0,19434
4,canonical_19k,media_count,19434,0,0,0,0,19434
5,canonical_19k,statuses_count,19434,0,0,0,0,19434
6,canonical_19k,user_age,19434,0,0,0,0,19434
7,canonical_19k,follower_growth_rate,19434,0,0,0,0,19434
8,canonical_19k,friends_growth_rate,19434,0,0,0,0,19434
9,canonical_19k,default_profile,19434,0,0,0,0,19434
10,canonical_19k,default_profile_image,19434,0,0,0,0,19434
11,canonical_19k,has_custom_timelines,19434,0,0,0,0,19434
12,canonical_19k,possibly_sensitive,19434,0,0,0,0,19434
13,canonical_19k,hashtag_in_description,19434,0,0,0,0,19434
14,canonical_19k,numbers_in_description,19434,0,0,0,0,19434
15,canonical_19k,no_type_tweet,19434,0,0,0,0,19434
16,canonical_19k,no_type_retweet_with_comment,19434,0,0,0,0,19434
17,canonical_19k,no_type_reply,19434,0,0,0,0,19434
18,canonical_19k,mean_no_media_per_tweet,19434,0,0,0,0,19434
19,canonical_19k,mean_no_words,19434,0,0,0,0,19434
20,canonical_19k,no_languages,19434,0,0,0,0,19434
21,canonical_19k,mean_no_hashtags,19434,0,0,0,0,19434
22,canonical_19k,mean_favourites_per_tweet,19434,0,0,0,0,19434
23,canonical_19k,time_between_tweets,19434,0,0,0,0,19434
24,canonical_19k,tweet_frequency,19434,0,0,0,0,19434
25,canonical_19k,min_tweets_per_hour,19434,0,0,0,0,19434
26,canonical_19k,min_tweets_per_day,19434,0,0,0,0,19434
27,canonical_19k,max_tweets_per_hour,19434,0,0,0,0,19434
28,canonical_19k,max_tweets_per_day,19434,0,0,0,0,19434
29,canonical_19k,max_occurence_of_same_gap,19434,0,0,0,0,19434
30,canonical_19k,unique_mention_rate_per_tweet,19434,0,0,0,0,19434
31,canonical_19k,mean_user_mentions_per_tweet,19434,0,0,0,0,19434
32,canonical_19k,retweet_as_tweet_rate,19434,0,30,0,30,19404
33,canonical_19k,no_retweet_tweets,19434,0,0,0,0,19434
34,canonical_19k,mean_retweets_per_tweet,19434,0,0,0,0,19434
35,canonical_19k,description_length,19434,6735,0,0,0,12699
36,canonical_19k,followers_friend_ratio,19434,4,0,0,0,19430
37,canonical_19k,num_digits_in_name,19434,0,0,0,0,19434
38,canonical_19k,num_digits_in_username,19434,0,0,0,0,19434
39,canonical_19k,url_in_description,19434,6735,0,0,0,12699

,feature,compared,disagreements,only_19k_observed,rule
0,followers_count,957,1,0,19K remains canonical regardless of label; no ...
1,friends_count,957,1,0,19K remains canonical regardless of label; no ...
2,favourites_count,959,1,0,19K remains canonical regardless of label; no ...
3,listed_count,959,1,0,19K remains canonical regardless of label; no ...
4,media_count,959,1,0,19K remains canonical regardless of label; no ...
5,statuses_count,959,0,0,19K remains canonical regardless of label; no ...
6,user_age,772,0,187,19K remains canonical regardless of label; no ...
7,follower_growth_rate,772,0,187,19K remains canonical regardless of label; no ...
8,friends_growth_rate,772,0,187,19K remains canonical regardless of label; no ...
9,default_profile,959,0,0,19K remains canonical regardless of label; no ...
10,default_profile_image,959,0,0,19K remains canonical regardless of label; no ...
11,has_custom_timelines,959,0,0,19K remains canonical regardless of label; no ...
12,possibly_sensitive,959,0,0,19K remains canonical regardless of label; no ...
13,hashtag_in_description,772,0,187,19K remains canonical regardless of label; no ...
14,numbers_in_description,772,0,187,19K remains canonical regardless of label; no ...
15,no_type_tweet,772,0,187,19K remains canonical regardless of label; no ...
16,no_type_retweet_with_comment,772,0,187,19K remains canonical regardless of label; no ...
17,no_type_reply,772,0,187,19K remains canonical regardless of label; no ...
18,mean_no_media_per_tweet,772,0,187,19K remains canonical regardless of label; no ...
19,mean_no_words,772,0,187,19K remains canonical regardless of label; no ...
20,no_languages,772,0,187,19K remains canonical regardless of label; no ...
21,mean_no_hashtags,772,0,187,19K remains canonical regardless of label; no ...
22,mean_favourites_per_tweet,772,0,187,19K remains canonical regardless of label; no ...
23,time_between_tweets,772,0,187,19K remains canonical regardless of label; no ...
24,tweet_frequency,772,0,187,19K remains canonical regardless of label; no ...
25,min_tweets_per_hour,772,0,187,19K remains canonical regardless of label; no ...
26,min_tweets_per_day,772,0,187,19K remains canonical regardless of label; no ...
27,max_tweets_per_hour,772,0,187,19K remains canonical regardless of label; no ...
28,max_tweets_per_day,772,0,187,19K remains canonical regardless of label; no ...
29,max_occurence_of_same_gap,772,0,187,19K remains canonical regardless of label; no ...
30,unique_mention_rate_per_tweet,772,0,187,19K remains canonical regardless of label; no ...
31,mean_user_mentions_per_tweet,772,0,187,19K remains canonical regardless of label; no ...
32,retweet_as_tweet_rate,772,0,187,19K remains canonical regardless of label; no ...
33,no_retweet_tweets,772,0,187,19K remains canonical regardless of label; no ...
34,mean_retweets_per_tweet,772,0,187,19K remains canonical regardless of label; no ...
35,description_length,915,0,0,19K remains canonical regardless of label; no ...
36,followers_friend_ratio,957,2,0,19K remains canonical regardless of label; no ...
37,num_digits_in_name,959,0,0,19K remains canonical regardless of label; no ...
38,num_digits_in_username,959,0,0,19K remains canonical regardless of label; no ...
39,url_in_description,915,0,0,19K remains canonical regardless of label; no ...

## 4. Temporal availability and missingness policy

Distinguish raw annotated coverage from raw 19K/canonical coverage. Increased coverage from
another observed source is not median imputation and does not imply complete timelines.
`provenance/temporal_by_user.csv` records per-feature source/availability for every user.

- `has_temporal`: at least one valid observed timing statistic.
- `temporal_complete`: all seven observed.
- `temporal_observed_count`: number observed.
- `observed__<feature>`: per-feature observation indicator before any tensor placeholder.

All users remain, including those with zero temporal observations. Temporal scalers fit only
observed training values. A feature with no training observations is disabled and recorded;
validation/test/unlabeled values cannot establish its transformation. Placeholder zeros are
never described as measured zero activity or estimated temporal observations.

In [4]:
display(run.reports['temporal_source_coverage'])
display(run.tables['provenance/temporal_by_user.csv'].head())

,source,users,any_temporal,complete_temporal,absent_temporal
0,annotated_binary_raw,959,772,772,187
1,canonical_binary_raw19k,959,959,959,0
2,canonical_unlabeled_raw19k,18331,18331,18331,0

,user_key,canonical_source,source_row_present_annotated,annotated_observed__time_between_tweets,canonical_observed__time_between_tweets,source__time_between_tweets,annotated_observed__tweet_frequency,canonical_observed__tweet_frequency,source__tweet_frequency,annotated_observed__min_tweets_per_hour,...,source__min_tweets_per_day,annotated_observed__max_tweets_per_hour,canonical_observed__max_tweets_per_hour,source__max_tweets_per_hour,annotated_observed__max_tweets_per_day,canonical_observed__max_tweets_per_day,source__max_tweets_per_day,annotated_observed__max_occurence_of_same_gap,canonical_observed__max_occurence_of_same_gap,source__max_occurence_of_same_gap
0,000terminator,accounts,False,False,True,raw_19k,False,True,raw_19k,False,...,raw_19k,False,True,raw_19k,False,True,raw_19k,False,True,raw_19k
1,007mi00,accounts,True,True,True,raw_19k,True,True,raw_19k,True,...,raw_19k,True,True,raw_19k,True,True,raw_19k,True,True,raw_19k
2,0080azad,accounts,False,False,True,raw_19k,False,True,raw_19k,False,...,raw_19k,False,True,raw_19k,False,True,raw_19k,False,True,raw_19k
3,00nietzsche,accounts,False,False,True,raw_19k,False,True,raw_19k,False,...,raw_19k,False,True,raw_19k,False,True,raw_19k,False,True,raw_19k
4,0100barg,accounts,False,False,True,raw_19k,False,True,raw_19k,False,...,raw_19k,False,True,raw_19k,False,True,raw_19k,False,True,raw_19k

## 5. Validate and preserve frozen user assignments

The saved assignment is an explicit research input. Check exact gold-user coverage, unique
normalized keys, unchanged labels, and both classes in every split. Invalid assignments fail
with an explanation; they are not replaced automatically. Modality availability is never an
eligibility filter. Historical repeated test inspection remains a reporting limitation.

In [5]:
display(run.freeze_splits())

        split  label_binary  users
0        test             0    116
1        test             1     28
2       train             0    540
3       train             1    131
4   unlabeled          <NA>  18331
5  validation             0    116
6  validation             1     28

## 6. Observed text preparation

Retain Persian normalization, emoji/hashtag evidence, within-user exact deduplication, the
historical train→validation→test text decontamination protocol, and up to 50 recent tweets.
Tie ordering is deterministic. Accounts losing all usable tweets stay in their frozen split.

Descriptions are prepared separately, with explicit raw/provided-clean source provenance.
`has_text` means usable tweets OR description; `has_tweet_text` and `has_description` remain
separate. A description vector must not silently replace a tweet vector downstream.
The historical token limit 128 is configuration, not a new choice based on held-out data.
No language-model download or embedding generation is required to run preprocessing.

In [6]:
display(run.prepare_text())
display(run.reports['tweet_time_quality'])

,split,raw_rows,after_within_user_dedup,after_decontamination,retained_tweets,users_with_text,all_users
0,train,45443,41846,41846,12976,671,671
1,validation,13968,10319,10152,2618,144,144
2,test,11464,10397,10249,3006,143,144
3,unlabeled,0,0,0,0,0,18331

    rows  missing_or_invalid_timestamp
0  70875                             0

## 7. Build graphs from observed follower/following lists

No legacy graph artifacts are loaded and no missing connections are predicted. Report malformed
lists and invalid handles; aggregate duplicate owner observations, deduplicate directed edges,
and count excluded self-edges. Keep edge-owner provenance separately from model edge lists.

Preserve the owner-centric graph protocol: gold endpoints belong to the same split as the
owner. External/unlabeled support users may overlap across graphs, so this is **not** fully
node-disjoint. The unlabeled-owner graph excludes validation/test gold endpoints.
Global graph exports are for audit/provenance only, not an authorized training graph.

Owner record, observed owner neighbors, prepared node membership, and usable owner graph
are separate flags. Every graph-unavailable user remains in the canonical population.

In [7]:
display(run.prepare_graph())
display(run.reports['graph_parse'].groupby(['field', 'state']).size().rename('source_rows'))
print('Invalid graph tokens:', int(run.reports['graph_parse']['invalid_tokens'].sum()))

        split  owner_users   nodes   edges  forbidden_gold_nodes
0       train          193   42954   60924                     0
1  validation           42   11436   13006                     0
2        test           41   10453   12536                     0
3   unlabeled         3033  190347  668329                     0

field      state
followers  nonempty         3442
following  nonempty         3442
owner      invalid_owner      11
Name: source_rows, dtype: int64

Invalid graph tokens: 11

## 8. Training-only transforms shared by all populations

Preserve the legacy log1p and RobustScaler choices. Non-temporal continuous features use
training medians; binary missing values use a documented training mode. Observed masks
remain available for both. Temporal features use observed-only scaling with no estimated fills.

The exact same fitted object transforms training, validation, test, and unlabeled users.
Canonical NaNs remain unchanged. Finite matrices, observation masks, modality masks, and
canonical user tables are exported separately and align by user_key. No learned feature
selection uses held-out users; the historical 40-feature design is explicitly retained.

In [8]:
display(run.fit_transform())
display(run.reports['fitted_statistics'])
display(run.users.groupby('split')[['has_profile', 'has_text', 'has_temporal', 'has_graph']].agg(['sum', 'count']))

        split  label_binary  users  available  complete
0        test             0    116        116       116
1        test             1     28         28        28
2       train             0    540        540       540
3       train             1    131        131       131
4   unlabeled          <NA>  18331      18331     18331
5  validation             0    116        116       116
6  validation             1     28         28        28

,feature,training_observations,enabled,temporal,binary,log1p,fill_value,center,scale
0,followers_count,670,True,False,False,True,6037.500000,8.705911,1.276954
1,friends_count,670,True,False,False,True,1575.000000,7.362645,2.014409
2,favourites_count,671,True,False,False,True,60888.000000,11.016808,1.642964
3,listed_count,671,True,False,False,True,9.000000,2.302585,1.791759
4,media_count,671,True,False,False,True,1682.000000,7.428333,1.534340
5,statuses_count,671,True,False,False,True,25845.000000,10.159911,1.649551
6,user_age,671,True,False,False,False,1908.000000,1908.000000,1946.500000
7,follower_growth_rate,671,True,False,False,True,4.329156,1.673193,1.079527
8,friends_growth_rate,671,True,False,False,True,0.730337,0.548316,0.958941
9,default_profile,671,True,False,True,False,1.000000,NaN,NaN
10,default_profile_image,671,True,False,True,False,0.000000,NaN,NaN
11,has_custom_timelines,671,True,False,True,False,1.000000,NaN,NaN
12,possibly_sensitive,671,True,False,True,False,0.000000,NaN,NaN
13,hashtag_in_description,671,True,False,True,False,0.000000,NaN,NaN
14,numbers_in_description,671,True,False,True,False,0.000000,NaN,NaN
15,no_type_tweet,671,True,False,False,True,4.000000,1.609438,2.545339
16,no_type_retweet_with_comment,671,True,False,False,True,1.000000,0.693147,1.386294
17,no_type_reply,671,True,False,False,True,1.000000,0.693147,2.197225
18,mean_no_media_per_tweet,671,True,False,False,False,0.800000,0.800000,0.642313
19,mean_no_words,671,True,False,False,True,24.612900,3.243096,0.731870
20,no_languages,671,True,False,False,True,1.000000,0.693147,0.693147
21,mean_no_hashtags,671,True,False,False,True,1.484912,0.910237,0.405465
22,mean_favourites_per_tweet,671,True,False,False,True,231.666700,5.449607,2.092914
23,time_between_tweets,671,True,True,False,True,NaN,13.075174,4.760155
24,tweet_frequency,671,True,True,False,True,NaN,2.712098,1.728729
25,min_tweets_per_hour,671,True,True,False,True,NaN,0.000000,1.000000
26,min_tweets_per_day,671,True,True,False,True,NaN,0.000000,0.693147
27,max_tweets_per_hour,671,True,True,False,True,NaN,1.098612,0.916291
28,max_tweets_per_day,671,True,True,False,True,NaN,1.098612,1.252763
29,max_occurence_of_same_gap,671,True,True,False,True,NaN,1.098612,1.252763
30,unique_mention_rate_per_tweet,671,True,False,False,True,0.076923,0.074108,0.287682
31,mean_user_mentions_per_tweet,671,True,False,False,True,0.156250,0.145182,0.521297
32,retweet_as_tweet_rate,671,True,False,False,True,3807.107143,8.244888,3.230819
33,no_retweet_tweets,671,True,False,False,True,25840.000000,10.159718,1.650332
34,mean_retweets_per_tweet,671,True,False,False,True,43.333330,3.791737,2.348919
35,description_length,643,True,False,False,False,86.000000,86.000000,87.000000
36,followers_friend_ratio,670,True,False,False,True,4.201164,1.648882,2.205658
37,num_digits_in_name,671,True,False,False,True,0.000000,0.000000,1.000000
38,num_digits_in_username,671,True,False,False,True,0.000000,0.000000,1.098612
39,url_in_description,643,True,False,True,False,0.000000,NaN,NaN

           has_profile        has_text        has_temporal        has_graph  \
                   sum  count      sum  count          sum  count       sum
split
test               144    144      144    144          144    144        41
train              671    671      671    671          671    671       193
unlabeled        18331  18331    11647  18331        18331  18331      3033
validation         144    144      144    144          144    144        42


            count
split
test          144
train         671
unlabeled   18331
validation    144

## 9. Validate before writing

Check preservation of every eligible gold user, frozen split membership, all-annotation
exclusion from the unlabeled pool, fit-user scope, temporal masks, finite numerical matrices,
feature ordering, text ownership/overlap, graph protocol, and unchanged input hashes.

In [9]:
display(run.validate())

                                       check  passed
0                       gold_users_preserved    True
1                           unique_user_keys    True
2         unlabeled_disjoint_all_annotations    True
3                     frozen_split_preserved    True
4                    training_fit_keys_exact    True
5                  temporal_mask_before_fill    True
6   temporal_canonical_missingness_preserved    True
7            no_cross_split_gold_graph_nodes    True
8                     source_files_unchanged    True
9                   train_all_users_retained    True
10                       train_finite_matrix    True
11                       train_feature_order    True
12                        train_aligned_keys    True
13        train_temporal_placeholders_masked    True
14               train_text_belongs_to_users    True
15             validation_all_users_retained    True
16                  validation_finite_matrix    True
17                  validation_feature_order    True
18                   validation_aligned_keys    True
19   validation_temporal_placeholders_masked    True
20          validation_text_belongs_to_users    True
21                   test_all_users_retained    True
22                        test_finite_matrix    True
23                        test_feature_order    True
24                         test_aligned_keys    True
25         test_temporal_placeholders_masked    True
26                test_text_belongs_to_users    True
27              unlabeled_all_users_retained    True
28                   unlabeled_finite_matrix    True
29                   unlabeled_feature_order    True
30                    unlabeled_aligned_keys    True
31    unlabeled_temporal_placeholders_masked    True
32           unlabeled_text_belongs_to_users    True
33           cross_split_exact_text_disjoint    True

## 10. Versioned export and disk-reload verification

Export only after checks pass. The fingerprint includes raw/configuration/split/code hashes
and runtime versions. The manifest is written last as the completion marker. Existing content
in a version is accepted only if byte-identical. No old artifacts are deleted or replaced.

Reload canonical users, matrices, masks, and the fitted preprocessor to reproduce transformed
values for all four populations and verify every artifact hash.

In [10]:
OUTPUT_DIR = run.export()
verification = verify_export(OUTPUT_DIR)
print('Completed version:', OUTPUT_DIR)
display(verification)

Completed version: C:\Users\p.vazifeh\Desktop\University\Project\Bot Detection Implementation\final_data\versions\preprocessing_v2_e861084d1a722a21

{'verified_artifacts': 60, 'reloaded_transform_populations': 4}

## 11. Notebook 03 handoff

Notebook 03 must explicitly select this version's manifest, read its `feature_order`, and
join the mask tables by user_key. No extra metadata/mask column may accidentally enter the
40-feature baseline. Missing-modality users must remain in evaluation. The new schema does
not silently replace legacy files or make old checkpoints compatible with changed inputs.

Required artifacts include `splits/users/`, `splits/tabular/`, `splits/masks/`, `splits/text/`,
`preprocessing/preprocessor.joblib`, `config/feature_registry.json`, and `manifest.json`.
The next phase will update baseline loading, checkpoint selection, and evaluation—not retrain
models inside this preprocessing notebook.

Limitations remain: small imbalanced human-annotated data, unknown aggregate derivations,
incomplete graph/timelines, unequal unlabeled text availability, and historical test reuse.