# 08 — Leakage-safe tabular semi-supervised learning

The unlabeled corpus has no retained tweet text. This is therefore a tabular pseudo-label experiment using the original Notebook-03 tabular MLP, not a multimodal-fusion experiment. The archived notebook remains preserved separately.

In [1]:
from pathlib import Path
import sys
ROOT = Path.cwd().resolve()
if not (ROOT / 'configs').exists():
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))
from src.semi_supervised import SemiSupervisedRun, verify_run

## Protocol and leakage boundaries

The teacher is the pinned Notebook-03 tabular MLP `last` checkpoint. Its predictions are reproduced on all frozen labeled splits before use. Only the 671 frozen training labels and truly unlabeled users may influence student gradients. Validation selects checkpoints; test is evaluation-only. Exact Phase-2 feature order and train-fitted transforms are reused without refitting.

In [2]:
run = SemiSupervisedRun(ROOT)
display(run.config)
print('Teacher:', run.teacher_path)
print('Frozen labeled training users:', len(run.labeled['keys']))
print('True unlabeled users:', len(run.unlabeled['users']))

{'schema_version': 'semi_supervised_tabular_v2',
 'phase2_manifest': 'final_data/versions/preprocessing_v2_e861084d1a722a21/manifest.json',
 'phase2_manifest_sha256': '594a2defef59d663ef171020b7cd1ba75aa321c30e7a7d09b57b560563c109c9',
 'baseline_manifest': 'results/versions/baselines_v2/20260916T103951409018Z_7fa575b7/manifest.json',
 'baseline_manifest_sha256': 'fd5c8a4d0d7f4728238fd9d7e495289117327fa2661bed676caffe3d92ef817c',
 'teacher_model': 'tabular_mlp',
 'teacher_checkpoint_variant': 'last',
 'student_initialization': 'pinned_teacher_state',
 'output_root': 'results/versions/semi_supervised_v2',
 'seed': 42,
 'device': 'cpu',
 'torch_threads': 1,
 'threshold': 0.5,
 'training': {'epochs': 50,
  'batch_size': 32,
  'lr': 0.001,
  'weight_decay': 0.0001,
  'selection': 'best_validation_loss'},
 'pseudo_label': {'confidence_threshold': 0.95,
  'pseudo_loss_coefficient': 0.5,
  'class_balanced_cap': 195,
  'human_selection': 'confidence_desc_then_user_key_asc_top_k',
  'bot_selection': 'retain_all_accepted',
  'sampling': 'none_deterministic_ranking',
  'selection_seed': 42},
 'expected': {'labeled_train': 671,
  'validation': 144,
  'test': 144,
  'unlabeled': 18331,
  'accepted_pseudo_bot': 195,
  'selected_pseudo_human': 195,
  'selected_pseudo_bot': 195}}

Teacher: C:\Users\p.vazifeh\Desktop\University\Project\Bot Detection Implementation\results\versions\baselines_v2\20260916T103951409018Z_7fa575b7\models\tabular_mlp_last.pt
Frozen labeled training users: 671
True unlabeled users: 18331

## Modality and temporal limitation

All 18,331 unlabeled users have profile/behavioral/temporal tabular values, but zero have retained tweet text. Descriptions are not substituted for tweets. Temporal values and observation masks remain Phase-2 outputs: no new imputation, timeline assumption, or temporal-based exclusion is introduced.

In [3]:
display(run.unlabeled['masks'].sum(numeric_only=True).to_frame('users'))
display(run.unlabeled['observed'].filter(like='observed__').sum().to_frame('observed_users'))

                            users
has_custom_timelines       5017.0
has_profile               18331.0
has_temporal              18331.0
has_behavior              18331.0
temporal_observed_count  128317.0
temporal_complete         18331.0
has_raw_tweets                0.0
has_tweet_text                0.0
has_description_raw       11646.0
has_description           11647.0
has_text                  11647.0
has_graph_owner_record     3033.0
has_graph_owner            3033.0
has_graph                  3033.0
has_graph_node            11463.0

                                         observed_users
observed__followers_count                         18329
observed__friends_count                           18329
observed__favourites_count                        18331
observed__listed_count                            18331
observed__media_count                             18331
observed__statuses_count                          18331
observed__user_age                                18331
observed__follower_growth_rate                    18331
observed__friends_growth_rate                     18331
observed__default_profile                         18331
observed__default_profile_image                   18331
observed__has_custom_timelines                    18331
observed__possibly_sensitive                      18331
observed__hashtag_in_description                  18331
observed__numbers_in_description                  18331
observed__no_type_tweet                           18331
observed__no_type_retweet_with_comment            18331
observed__no_type_reply                           18331
observed__mean_no_media_per_tweet                 18331
observed__mean_no_words                           18331
observed__no_languages                            18331
observed__mean_no_hashtags                        18331
observed__mean_favourites_per_tweet               18331
observed__time_between_tweets                     18331
observed__tweet_frequency                         18331
observed__min_tweets_per_hour                     18331
observed__min_tweets_per_day                      18331
observed__max_tweets_per_hour                     18331
observed__max_tweets_per_day                      18331
observed__max_occurence_of_same_gap               18331
observed__unique_mention_rate_per_tweet           18331
observed__mean_user_mentions_per_tweet            18331
observed__retweet_as_tweet_rate                   18301
observed__no_retweet_tweets                       18331
observed__mean_retweets_per_tweet                 18331
observed__description_length                      11646
observed__followers_friend_ratio                  18329
observed__num_digits_in_name                      18331
observed__num_digits_in_username                  18331
observed__url_in_description                      11646

## Pseudo-label selection

The full teacher pseudo-label pool is retained. Threshold acceptance is symmetric at confidence ≥ 0.95. It yields 13,782 human and 195 bot candidates. The approved class-balanced training pool retains all 195 bots and exactly 195 humans, ranked by descending confidence then ascending `user_key`. This is deterministic; selection seed 42 is recorded even though no random sampling occurs.

In [4]:
display(run.pool.groupby(['accepted_by_threshold', 'pseudo_label']).size().rename('users').reset_index())
display(run.selected[['user_key', 'pseudo_label', 'confidence', 'selection_status']].head())
print(run.selected.pseudo_label.value_counts().sort_index().to_dict())

   accepted_by_threshold  pseudo_label  users
0                  False             0   3066
1                  False             1   1288
2                   True             0  13782
3                   True             1    195

          user_key  pseudo_label  confidence      selection_status
0  1m1peacefighter             0    1.000000  selected_for_student
1        288_hamid             0    1.000000  selected_for_student
2        46_yazdan             1    0.977211  selected_for_student
3  4womlifefreedom             1    0.992524  selected_for_student
4          76eng76             0    1.000000  selected_for_student

{0: 195, 1: 195}

## Continuation control and pseudo student

Both models start from the identical teacher state and run 50 extra epochs using the original 40→64→32→1 tabular MLP, BatchNorm, dropout 0.3, BCE loss weighting, AdamW, batch size 32 and validation-loss selection. The control receives labeled training batches only. The student receives a paired pseudo batch with confidence-weighted loss multiplied by the approved coefficient 0.5. This makes the larger unlabeled pool unable to dominate merely by its size.

In [5]:
run.fit()
for name, history in run.histories.items():
    print(name, run.info[name])
    display(history)

labeled_control epoch 10: {'epoch': 10, 'labeled_loss': 0.5344658607528323, 'pseudo_loss': 0.0, 'validation_loss': 1.4645612239837646}

labeled_control epoch 20: {'epoch': 20, 'labeled_loss': 0.4692572227546147, 'pseudo_loss': 0.0, 'validation_loss': 1.481703519821167}

labeled_control epoch 30: {'epoch': 30, 'labeled_loss': 0.46351501771381926, 'pseudo_loss': 0.0, 'validation_loss': 1.587451457977295}

labeled_control epoch 40: {'epoch': 40, 'labeled_loss': 0.3959335358369918, 'pseudo_loss': 0.0, 'validation_loss': 1.7039299011230469}

labeled_control epoch 50: {'epoch': 50, 'labeled_loss': 0.43379525130703334, 'pseudo_loss': 0.0, 'validation_loss': 1.8470900058746338}

pseudo_student epoch 10: {'epoch': 10, 'labeled_loss': 0.5516334076722463, 'pseudo_loss': 0.11640611104667187, 'validation_loss': 1.2549017667770386}

pseudo_student epoch 20: {'epoch': 20, 'labeled_loss': 0.5075521185284569, 'pseudo_loss': 0.042475963942706585, 'validation_loss': 1.3239712715148926}

pseudo_student epoch 30: {'epoch': 30, 'labeled_loss': 0.46293366097268607, 'pseudo_loss': 0.035831070660303034, 'validation_loss': 1.4286161661148071}

pseudo_student epoch 40: {'epoch': 40, 'labeled_loss': 0.46126329047339304, 'pseudo_loss': 0.02752648839460952, 'validation_loss': 1.42807936668396}

pseudo_student epoch 50: {'epoch': 50, 'labeled_loss': 0.4808718271198727, 'pseudo_loss': 0.013128344923080433, 'validation_loss': 1.6541156768798828}

labeled_control {'best_epoch': 6, 'last_epoch': 50, 'selection': 'best_validation_loss', 'pos_weight': 4.122137546539307, 'labeled_training_user_keys': ['dokhi_sag', 'history_wall', 'corrrdeliiiaaa', 'ahmad_313m', 'kouresh_kabir', 'zone7689', 'rahar9075', 'rahayee_', 'nadersoltanpour', 'fatemeh_sadat91', 'nilabehzadi', 'nokhod_f', 'dariush_omran', 'xpishik', 'farhadiivar', 'savasavadkoohi', 'soozi2244', 'tnitrt', 'moslehiali', 'khormal0098', 'thank_you_dj', 'kingbacker1', 'fattahifarzad', 'sasanamjadi', 'cafeandisheh', 'noodlesss1990', 'sokoot3333', 'caramelcakeeee', 'cheguevara_amir', 'persian_warior', 'knightanahita19', 'birdofpeacelove', 'itskouroshkabir', 'sandys_khor', 'siavash_sepehr0', 'vanheda97', 'stupidjalal', 'iranovsky', 'riokhosravi', 'radiomashrooteh', 'yepremkhann', 'davariabdolreza', 'sepideh52191550', 'irtimes', 'fxmndlsn', 'avantgardearses', 'mahdavileily', 'maryam_rajavi', 'rahaaaman', 'mahsa_300', 'agha_rashti2', 'maanii_a', 'armin19910215', 'majidtavakolii', 'overthrower_', 'benyamin_aras', 'reptile_fight', 'rezas27', 'zarei_arad', 'armanjasoor', '2002kingfox', 'inazkam', 'xbx73mol77qbath', 'parspersian', 'mmlekate', 'hossein_68_38', 'm0rtezaaaa', 'shahrammakoui48', 'pirouzimm', 'mahmoud55791825', 'pahlavi433726', 'pmoiran', 'nasrinraj', 'tinaaa2048', 'psrasfhan27734', 'kshahrooz', 'mobarez_nastooh', 'pahlavi_davoud', 'solo_commando', 'mihanimarzban03', 'siaayrom', 'miladpoureisa', 'fairghh', 'kaykhosrow5', 'nimania', 'khosrowalikord2', 'rayan9717', 'amin1917', 'najibnaik', 'neo_pahlavism1', 'iraniazad140', 'ebrahimi_mazyar', 'kouroch7', 'ab_ganji', 'hiran_irani', 'ghorbaniiniyak', 'ladyjusticeiran', 'limondar0', 'shirkhaan69', 'behzadhamrahi', 'ivar_lathbrug2', 'majidirani99', 'mooniter', 'irandokht_20', 'mohammadsigari', 'locallandia', 'ba262626', 'darksheeprise', 'the_doonald', 'sonofthebeach22', 'ted_homan1361', 'amiretemadi', 'milaniabbas', 'danamehraban', 'fakhravar', 'azadlavasani', 'adam_hesabi1', 'tonyfreeman2015', 'merlin_a_h', 'shadisadr', 'radmehrsiavash', 'rasulbajelan', 'ali_bitarafan5', 'iraj63569385', 'mard_meshki', 'arteshariamehr', 'darwinsabouri', 'tanha_5566', 'kayvanabbassi', 'liberalartist00', 'irannewsagency0', 'zimmermann____', 'nastaran8888', 'dariush2023', 'shirinkhanomam', 'amirmoghadam_ir', 'aminkhss', 'alinaghi2018', 'sushyanpahlavi', 'protester0101', 'shino_sdch', 'kasrakarimi3', 'fazel_twt', 'agha_xavier2', 'awat_baggio', 'itshamedfard', 'hardseltzerr', 'moradian_ir', 'arash_tehran', 'yasipatriot', 'alinejadmasih', 'cemalk25777cema', 'brgsht8970', 'realpersiangod', 'ardavanmofid', 'hananyapersian', 'eboshijasmine', 'golberg2582', 'mayrayazdari', 'accuracyhhm', 'radoclub', 'ftmh_zhra_jnde', 'madarisarzamin', 'hadint83', 'keykemiveyi', 'nasim_zephyr', 'fali1969', 'pantearasouli', 'firstzorba1', 'kouli2017', 'reddington_la', 'jalilparsi', 'hosseinashtarii', 'shooresh57', 'vajname', 'anubis_god2', 'aramofen', 'viemonx', 'roshanak_ast', 'amir41355273', 'arrested_voice', 'mohammadd4456', 'mohammadsaam_m', 'ghassemiabi', 'me_unstoppable2', 'pouriazeraati', 'taramedric', 'bardiagarshasbi', 'fcpii_official', 'aliemamiofnyc', 'kfravahar', 'yebekhe', 'hosein_golzar75', 'scorpionofiran1', 'bermooda1380739', 'lexi__princess', 'iranaryan2579', 'naghmel', '_hassan_sabbah_', 'trollsiasi', 'oshtb', 'iraanbaan', 'belovediraaaan', 'artesh_shah', 'bb_goal', 'mahizadyaar', 'cpiparty', 'azadsocial_', 'siavosh48', 'koteh_bamishi', 'jo5x8hatcf3o5px', 'mrhosein00', 'baaarzaaakh', 'yyh8x5hc6nxh1wd', 'mabi182', 'greywol08482159', 'l0mpan', 'georg_patriot', 'jabijoon26588', 'adam_hesabi', 'lawdanbazargan', 'ssaallaar', 'delban_sa', 'realfarid7', 'nilgonbanoo', 'tymsar2578', 'im_zhozefin', 'shahira60210003', 'mohammadsoltann', 'ariyaii_rahjoo', 'esmaeilion', 'atheistchild789', 'keyonek1', 'hegei_javan', 'netvand', 'ladikhanom', 'sssccpp', 'kourosh634', 'ahampay', 'iraj_mesdaghi', 'enferadi_shode', 'rezarez11109331', 'chehre3521', 'nazanin7', 'proudlypersian1', 'rufusbeyn', 'starbombair', 'bob00033791', 'pasargadguard', 'mandela08940434', 'hoda2728', 'panteapeyvandi', 'afshari_aku', 'mehdimmj', 'shahii1984', 'javadsimin', '6njeli', 'hajmaameed', 'rezayyyyyyy', 'megamaniran', 'hosseinghatib', 'mard62881776', 'rezavaisi', 'eliiranabad', 'janankhorram', 'iranimmortals', 'baranaryaee2', 'king_fishpoet', 'napelon_daii', 'jwd06342045', 'sohrab_siyavosh', '5anazazana5', 'bahram2541', 'upuouo', 'voltaireiran', 'akhoondemorde', 'sadaf__12', 'bachejirjirak', 'ffarhad7412', 'aokurucz', 'gard_e_javidan', 'sirous15', 'rezakh__', 'sheyda_ri', 'alirzadabir', 'nafasjan903269', 'siamakghassemi', 'aryammehr_2', 'farshadeashour', 'sheina__', 'kharmagas_uk', 'akhtar1989', 'max_mad777', 'baran27922', 'margbar3fased', 'alireza7553', 'prime_factor_', 'arad60292050', 'rezatorkamand', 'kharkhali', 'samirkh1389', 'drfalahatpishe', 'bahar00452227', 'hichkasofficial', 'aalchaa', 'sasanrahimpour1', 'zootopiazz', 'inventor_kevin', 'peacehappyjoy', 'iraneshghal', 'ahmadysetareh', 'behzadzara', 'hamidsanati6661', 'ryaniran', 'mahnush_a', 'peleja11', 'ansari_bahman', 'kamran99575602', 'iranistics_ut', 'lilium52709755', 'naaserxa', 'kamranmatin', 'alialimartin893', 'crissss_sh', 'vahid__bahman', 'behrouzjt', 'tondbad3', 'karimsnowman', 'zananfirouzehie', 'mahrokh19726311', 'bardi1980', 'iran_javid863', 'tahsinzhaleh', 'tanhatak5112', 'samadihosein', 'chawshin_83', 'omiddana19', 'nikipatriot', 'amirhadianvari', 'amiinmosavii94', 'yrneszv9zrlixuq', 'iranimamoka', 'mirakh838', 'camel6561', 'khalaji_mehdi', 'r0tterdamer', 'fereydounjrl', 'atheistcyrus', 'ario1401', 'adlin_shehulk', 'diiyako_ir', 'ketn7912', 'alizolg85051503', 'abdolah_abdi', 'chetoriarzeshi', 'bobbyheravi', 'antythezis', 'iran_mehr_2016', 'servinpooryamin', 'runykeyoldpics', 'bashirtash', 'chenahaara', 'persepolis78', 'imnotmarsh', 'yaamaashitaa', 'searusm', 'baharr_ali', 'king_sarab47', 'genjahanbani', 'eghbalibabak', 'forouzandy', 'rezas49', 'homeyramis', 'sho_ber_5', 'fariba60867811', 'sedaye_mardoom', 'babakshekarabi', 'morrysafi', 'flexcr7', 'estemnayi1', 'bparnian1', 'fuzakeruna16', 'lisadaftari', 'siamakfarid', 'verethragnan', 'israelrouydad', 'aryaieeasil', 'hiwatubeai2', 'angelonduty06', 'hadinik', 'saman_sarraf', 'foster_spar', 'california123aa', 'suuoozanam', 'shahnazteherani', 'gh0lch0magh', 'ariamehr104', 'rahe_azadi_5', 'iranaxis', 'alighazizade', 'saeed_akbari39', 'policenama1401', 'pirooz25372', 'pirozzzzzzzzz', 'shawnaazad2', 'majidfallah11', 'arezoubehrang_', 'mehranshirazii', 'iranianarts', 'shaya9000', 'samanarbabi', 'piishgoo', 'kalaq666', 'benisabti', 'katierebel2nd', 'hosseinirouzbeh', 'arminnavabi', 'nasrinrose1', 'simurgh2580', 'steveimcqueen', 'h_2arya', 'mohammad2zab', 'imdearie2', 'persian_picture', 'golrokhiraee', 'abelbalb', 'sanazazanas', 'vidasarafraz', 'kathymobarez', 'marianmeyer0', 'hossein_d15', 'mardomakonline', 'ariaomid', 'parvin965631051', 'pahlaviahoraeep', 'laklak_muzik', 'sadeghzibakalam', 'bamdadpirouzi', 'mohajraniran', 'hadimehrane1', 'sababakhtyari', 'rustamasoud', 'ardeshir1387', 'onlymuratt', 'abidel23952698', 'iman_inj', 'honarparvar2020', 'ebne_noah', 'iranlionness', 'benyami1980', 'shirzad1968', 'shaheen_ir', 'hightesla', 'saeed48920740', 'bugsbuny90', 'nooralitoon', 'trumppersia', 'f7_arash', 'salmansima', 'shayan_shahnazi', '____rohi____', 'tondar1985', 'hosseintajik07', 'arashir22142540', 'ariaroshangar', 'dkhos', 'hassanshariatm5', 'amoopoya', 'proshahanshaahi', 'jashnimitra', 'eisa_1355', 'zarin_farzad', 'ordinaryman1980', 'chamli69', 'dariush25371', 'safa_8863', 'pedar_bozorgggg', 'noushaeshghi', 'omidam_hamin', 'jahangirtaban', 'damdami', 'rageandhope', 'obeydzacany', 'nickkhoo_arash', 'ebnehava', 'behrouzboochani', 'baraye_azadi_', 'sazanist40', 'majid53866855', 'haleh_panzer', 'samar_iran', 'uomomees', 'ggehhry2', 'masoudslii', 'irbozorg', 'mostafaa_karimi', 'saiedehsaideh59', 'kambizghafouri', 'mehdihajati', 'jiar06731264', 'd0wn_under', 'golestanparsa', 'barfiiiran', 'iranplateau1', 'a_jafarzadeh', 'aliaghell', 'neda73neda', 'marie36822764', 'mahistan', 'parwaz22', 'mahmoudzibaie', 'sedaye_iran', 'saba_khoi', 'peroz401939762', 'majidh44995071', '0mhp037', 'schahrzad_b', 'mery202120', 'masad75405681', 'khatibiofficial', 'smjm1972', 'rezahashemi1919', 'masioob', 'me_hamed_myself', 'pegah_shirazi', 'havin_n5', 'toukaneyestani', 'faranakazad1', 'naslsokhteh60', 'iran_vdt', 'navidi49', 'green_amir', 'sarbazeh_vatan1', 'frarandeh', 'radman2576', 'young_sheldon1', 'malusakam', 'roshangarnasl', 'navidmajd11', 'alihamid27', '__injaneb96', 'hzarkesh', 'mahdieh_golroo', 'amooamirkhan', 'antiprop_aganda', 'alireza_hafezi1', 'bahar_e_azadi', 'abornaei', '_ashkaval_', 'quietgirl7319', 'jalovemila', 'pahlavikhah43', 'patrick_jane77', 'mahboubeh_mdi', 'satggin', 'shahiavid', 'with_pahlavi3', 'rppress0', 'saramobarez1', 'miss_maropelle', 'silmaethdante', 'dargoldan2', 'nastaran9638495', 'loabatk', 'vahid_esmaeilii', 'soheili84', 'mayekhal', 'mr20228', 'sinatoossi', 'roshanaeii', 'lnahalllnahall', 'darushirani13', 'addison77866447', 'parand____', '2expvzwq7llpx4p', 'hs_maryam', 'memarsadeghi', 'mollah', 'sashtyani', 'hastyarrr', 'daystar98173834', 'aghachurchill', 'drshehabp', 'yarabaydad', 'angel71as', 'azarbayjanx', 'kamalpishvandi', 'farbodahmadi880', 'omid_av2', 'medinfo_x', 'hambastegi', 'twittbirds7', 'bernoam', 'majidazarpey', 'naeimehdoustdar', 'sababagherii', 'mashinmonee', 'shararehtalaeii', 'hekasrehcrisis', 'mazdakbamdadan2', 'iranariyayi64', 'mojtabanikoo', 'koroshcr7', 'mhrdadbarandaz3', 'aplcarolinedr', 'mahnazshirali', 'far_yaddd', 'arianarian00', 'hhellfireeeeee', 'seedhossein2111', 'shaheenchevv', 'mashrotehorg', 'nemo_regnum', 'ali49781135', 'ariamehhr', 'mehr_mihan', 'nasehmohi', 'aazadian2005', 'sfaeze_alavi', 'roobahyab1', 'freedom_of_ir', 'cameronbehzadi', 'rosebuddonkhoan', 'safaidarya', 'soleymaniazadeh', 'azadchakavak', 'freeman010', 'sangtarash_azad', 'pahlavi_yasmine', 'iran_farda1', 'gohareshghi', 'matinkhaledii', '2tosgzcfj8vtsjk', 'shah_parast_k', 'sheykhbabar2', 'jooldooz', 'lishaghayeghli', 'nargesfnd', 'tomasshellllby', 'shdelfan', 'libertyiranian', 'naslesookhtehh', 'javidshah0000', '007mi00', 'dawnandthex', 'leiliii27', 'beevan88', 'persiangw', 'x4lirez4x', 'omidkt62', 'kiarashfarasat1', 'saeid_555555', 'm_ojmal', 'djhastammoho', 'iranzad_98', 'itisbatgirl', 'liberti2022', 'remisgp', 'haniiiissss1387', 'yaldarod', 'mojgan07798961', 'powerpeople_', 'iran22851566', 'amiriysara', 'jc_constantine1', 'ddsbobby', 'tanha59977799', 'santamorte00', 'artemizshahdokh', 'cowboy_datoboy', 'javidaniranema'], 'pseudo_training_user_keys': [], 'pseudo_draws': 0, 'initialization': 'pinned_teacher_state', 'checkpoints': {'best_validation_loss': 'models/labeled_control_best_validation_loss.pt', 'last': 'models/labeled_control_last.pt'}}

    epoch  labeled_loss  pseudo_loss  validation_loss
0       1      0.507006          0.0         1.379115
1       2      0.528627          0.0         1.382866
2       3      0.495317          0.0         1.401482
3       4      0.542746          0.0         1.412595
4       5      0.533312          0.0         1.405751
5       6      0.516728          0.0         1.336407
6       7      0.551420          0.0         1.411664
7       8      0.539086          0.0         1.441619
8       9      0.503478          0.0         1.433710
9      10      0.534466          0.0         1.464561
10     11      0.533958          0.0         1.363122
11     12      0.478368          0.0         1.420241
12     13      0.461684          0.0         1.455966
13     14      0.535444          0.0         1.490475
14     15      0.507270          0.0         1.514386
15     16      0.503165          0.0         1.472252
16     17      0.498695          0.0         1.492276
17     18      0.466372          0.0         1.525886
18     19      0.477051          0.0         1.533119
19     20      0.469257          0.0         1.481704
20     21      0.458806          0.0         1.536998
21     22      0.507625          0.0         1.552299
22     23      0.468383          0.0         1.621782
23     24      0.474203          0.0         1.594293
24     25      0.464953          0.0         1.616738
25     26      0.458259          0.0         1.661569
26     27      0.533087          0.0         1.619940
27     28      0.418640          0.0         1.568073
28     29      0.489819          0.0         1.590373
29     30      0.463515          0.0         1.587451
30     31      0.420762          0.0         1.630310
31     32      0.494964          0.0         1.659405
32     33      0.465090          0.0         1.646289
33     34      0.407368          0.0         1.660398
34     35      0.443382          0.0         1.576396
35     36      0.473596          0.0         1.592017
36     37      0.488618          0.0         1.651495
37     38      0.475721          0.0         1.673830
38     39      0.388156          0.0         1.684828
39     40      0.395934          0.0         1.703930
40     41      0.447028          0.0         1.753661
41     42      0.437086          0.0         1.861833
42     43      0.444783          0.0         1.601814
43     44      0.529769          0.0         1.698248
44     45      0.406333          0.0         1.689824
45     46      0.417136          0.0         1.736748
46     47      0.481012          0.0         1.735049
47     48      0.423905          0.0         1.741442
48     49      0.439041          0.0         1.761230
49     50      0.433795          0.0         1.847090

pseudo_student {'best_epoch': 1, 'last_epoch': 50, 'selection': 'best_validation_loss', 'pos_weight': 4.122137546539307, 'labeled_training_user_keys': ['dokhi_sag', 'history_wall', 'corrrdeliiiaaa', 'ahmad_313m', 'kouresh_kabir', 'zone7689', 'rahar9075', 'rahayee_', 'nadersoltanpour', 'fatemeh_sadat91', 'nilabehzadi', 'nokhod_f', 'dariush_omran', 'xpishik', 'farhadiivar', 'savasavadkoohi', 'soozi2244', 'tnitrt', 'moslehiali', 'khormal0098', 'thank_you_dj', 'kingbacker1', 'fattahifarzad', 'sasanamjadi', 'cafeandisheh', 'noodlesss1990', 'sokoot3333', 'caramelcakeeee', 'cheguevara_amir', 'persian_warior', 'knightanahita19', 'birdofpeacelove', 'itskouroshkabir', 'sandys_khor', 'siavash_sepehr0', 'vanheda97', 'stupidjalal', 'iranovsky', 'riokhosravi', 'radiomashrooteh', 'yepremkhann', 'davariabdolreza', 'sepideh52191550', 'irtimes', 'fxmndlsn', 'avantgardearses', 'mahdavileily', 'maryam_rajavi', 'rahaaaman', 'mahsa_300', 'agha_rashti2', 'maanii_a', 'armin19910215', 'majidtavakolii', 'overthrower_', 'benyamin_aras', 'reptile_fight', 'rezas27', 'zarei_arad', 'armanjasoor', '2002kingfox', 'inazkam', 'xbx73mol77qbath', 'parspersian', 'mmlekate', 'hossein_68_38', 'm0rtezaaaa', 'shahrammakoui48', 'pirouzimm', 'mahmoud55791825', 'pahlavi433726', 'pmoiran', 'nasrinraj', 'tinaaa2048', 'psrasfhan27734', 'kshahrooz', 'mobarez_nastooh', 'pahlavi_davoud', 'solo_commando', 'mihanimarzban03', 'siaayrom', 'miladpoureisa', 'fairghh', 'kaykhosrow5', 'nimania', 'khosrowalikord2', 'rayan9717', 'amin1917', 'najibnaik', 'neo_pahlavism1', 'iraniazad140', 'ebrahimi_mazyar', 'kouroch7', 'ab_ganji', 'hiran_irani', 'ghorbaniiniyak', 'ladyjusticeiran', 'limondar0', 'shirkhaan69', 'behzadhamrahi', 'ivar_lathbrug2', 'majidirani99', 'mooniter', 'irandokht_20', 'mohammadsigari', 'locallandia', 'ba262626', 'darksheeprise', 'the_doonald', 'sonofthebeach22', 'ted_homan1361', 'amiretemadi', 'milaniabbas', 'danamehraban', 'fakhravar', 'azadlavasani', 'adam_hesabi1', 'tonyfreeman2015', 'merlin_a_h', 'shadisadr', 'radmehrsiavash', 'rasulbajelan', 'ali_bitarafan5', 'iraj63569385', 'mard_meshki', 'arteshariamehr', 'darwinsabouri', 'tanha_5566', 'kayvanabbassi', 'liberalartist00', 'irannewsagency0', 'zimmermann____', 'nastaran8888', 'dariush2023', 'shirinkhanomam', 'amirmoghadam_ir', 'aminkhss', 'alinaghi2018', 'sushyanpahlavi', 'protester0101', 'shino_sdch', 'kasrakarimi3', 'fazel_twt', 'agha_xavier2', 'awat_baggio', 'itshamedfard', 'hardseltzerr', 'moradian_ir', 'arash_tehran', 'yasipatriot', 'alinejadmasih', 'cemalk25777cema', 'brgsht8970', 'realpersiangod', 'ardavanmofid', 'hananyapersian', 'eboshijasmine', 'golberg2582', 'mayrayazdari', 'accuracyhhm', 'radoclub', 'ftmh_zhra_jnde', 'madarisarzamin', 'hadint83', 'keykemiveyi', 'nasim_zephyr', 'fali1969', 'pantearasouli', 'firstzorba1', 'kouli2017', 'reddington_la', 'jalilparsi', 'hosseinashtarii', 'shooresh57', 'vajname', 'anubis_god2', 'aramofen', 'viemonx', 'roshanak_ast', 'amir41355273', 'arrested_voice', 'mohammadd4456', 'mohammadsaam_m', 'ghassemiabi', 'me_unstoppable2', 'pouriazeraati', 'taramedric', 'bardiagarshasbi', 'fcpii_official', 'aliemamiofnyc', 'kfravahar', 'yebekhe', 'hosein_golzar75', 'scorpionofiran1', 'bermooda1380739', 'lexi__princess', 'iranaryan2579', 'naghmel', '_hassan_sabbah_', 'trollsiasi', 'oshtb', 'iraanbaan', 'belovediraaaan', 'artesh_shah', 'bb_goal', 'mahizadyaar', 'cpiparty', 'azadsocial_', 'siavosh48', 'koteh_bamishi', 'jo5x8hatcf3o5px', 'mrhosein00', 'baaarzaaakh', 'yyh8x5hc6nxh1wd', 'mabi182', 'greywol08482159', 'l0mpan', 'georg_patriot', 'jabijoon26588', 'adam_hesabi', 'lawdanbazargan', 'ssaallaar', 'delban_sa', 'realfarid7', 'nilgonbanoo', 'tymsar2578', 'im_zhozefin', 'shahira60210003', 'mohammadsoltann', 'ariyaii_rahjoo', 'esmaeilion', 'atheistchild789', 'keyonek1', 'hegei_javan', 'netvand', 'ladikhanom', 'sssccpp', 'kourosh634', 'ahampay', 'iraj_mesdaghi', 'enferadi_shode', 'rezarez11109331', 'chehre3521', 'nazanin7', 'proudlypersian1', 'rufusbeyn', 'starbombair', 'bob00033791', 'pasargadguard', 'mandela08940434', 'hoda2728', 'panteapeyvandi', 'afshari_aku', 'mehdimmj', 'shahii1984', 'javadsimin', '6njeli', 'hajmaameed', 'rezayyyyyyy', 'megamaniran', 'hosseinghatib', 'mard62881776', 'rezavaisi', 'eliiranabad', 'janankhorram', 'iranimmortals', 'baranaryaee2', 'king_fishpoet', 'napelon_daii', 'jwd06342045', 'sohrab_siyavosh', '5anazazana5', 'bahram2541', 'upuouo', 'voltaireiran', 'akhoondemorde', 'sadaf__12', 'bachejirjirak', 'ffarhad7412', 'aokurucz', 'gard_e_javidan', 'sirous15', 'rezakh__', 'sheyda_ri', 'alirzadabir', 'nafasjan903269', 'siamakghassemi', 'aryammehr_2', 'farshadeashour', 'sheina__', 'kharmagas_uk', 'akhtar1989', 'max_mad777', 'baran27922', 'margbar3fased', 'alireza7553', 'prime_factor_', 'arad60292050', 'rezatorkamand', 'kharkhali', 'samirkh1389', 'drfalahatpishe', 'bahar00452227', 'hichkasofficial', 'aalchaa', 'sasanrahimpour1', 'zootopiazz', 'inventor_kevin', 'peacehappyjoy', 'iraneshghal', 'ahmadysetareh', 'behzadzara', 'hamidsanati6661', 'ryaniran', 'mahnush_a', 'peleja11', 'ansari_bahman', 'kamran99575602', 'iranistics_ut', 'lilium52709755', 'naaserxa', 'kamranmatin', 'alialimartin893', 'crissss_sh', 'vahid__bahman', 'behrouzjt', 'tondbad3', 'karimsnowman', 'zananfirouzehie', 'mahrokh19726311', 'bardi1980', 'iran_javid863', 'tahsinzhaleh', 'tanhatak5112', 'samadihosein', 'chawshin_83', 'omiddana19', 'nikipatriot', 'amirhadianvari', 'amiinmosavii94', 'yrneszv9zrlixuq', 'iranimamoka', 'mirakh838', 'camel6561', 'khalaji_mehdi', 'r0tterdamer', 'fereydounjrl', 'atheistcyrus', 'ario1401', 'adlin_shehulk', 'diiyako_ir', 'ketn7912', 'alizolg85051503', 'abdolah_abdi', 'chetoriarzeshi', 'bobbyheravi', 'antythezis', 'iran_mehr_2016', 'servinpooryamin', 'runykeyoldpics', 'bashirtash', 'chenahaara', 'persepolis78', 'imnotmarsh', 'yaamaashitaa', 'searusm', 'baharr_ali', 'king_sarab47', 'genjahanbani', 'eghbalibabak', 'forouzandy', 'rezas49', 'homeyramis', 'sho_ber_5', 'fariba60867811', 'sedaye_mardoom', 'babakshekarabi', 'morrysafi', 'flexcr7', 'estemnayi1', 'bparnian1', 'fuzakeruna16', 'lisadaftari', 'siamakfarid', 'verethragnan', 'israelrouydad', 'aryaieeasil', 'hiwatubeai2', 'angelonduty06', 'hadinik', 'saman_sarraf', 'foster_spar', 'california123aa', 'suuoozanam', 'shahnazteherani', 'gh0lch0magh', 'ariamehr104', 'rahe_azadi_5', 'iranaxis', 'alighazizade', 'saeed_akbari39', 'policenama1401', 'pirooz25372', 'pirozzzzzzzzz', 'shawnaazad2', 'majidfallah11', 'arezoubehrang_', 'mehranshirazii', 'iranianarts', 'shaya9000', 'samanarbabi', 'piishgoo', 'kalaq666', 'benisabti', 'katierebel2nd', 'hosseinirouzbeh', 'arminnavabi', 'nasrinrose1', 'simurgh2580', 'steveimcqueen', 'h_2arya', 'mohammad2zab', 'imdearie2', 'persian_picture', 'golrokhiraee', 'abelbalb', 'sanazazanas', 'vidasarafraz', 'kathymobarez', 'marianmeyer0', 'hossein_d15', 'mardomakonline', 'ariaomid', 'parvin965631051', 'pahlaviahoraeep', 'laklak_muzik', 'sadeghzibakalam', 'bamdadpirouzi', 'mohajraniran', 'hadimehrane1', 'sababakhtyari', 'rustamasoud', 'ardeshir1387', 'onlymuratt', 'abidel23952698', 'iman_inj', 'honarparvar2020', 'ebne_noah', 'iranlionness', 'benyami1980', 'shirzad1968', 'shaheen_ir', 'hightesla', 'saeed48920740', 'bugsbuny90', 'nooralitoon', 'trumppersia', 'f7_arash', 'salmansima', 'shayan_shahnazi', '____rohi____', 'tondar1985', 'hosseintajik07', 'arashir22142540', 'ariaroshangar', 'dkhos', 'hassanshariatm5', 'amoopoya', 'proshahanshaahi', 'jashnimitra', 'eisa_1355', 'zarin_farzad', 'ordinaryman1980', 'chamli69', 'dariush25371', 'safa_8863', 'pedar_bozorgggg', 'noushaeshghi', 'omidam_hamin', 'jahangirtaban', 'damdami', 'rageandhope', 'obeydzacany', 'nickkhoo_arash', 'ebnehava', 'behrouzboochani', 'baraye_azadi_', 'sazanist40', 'majid53866855', 'haleh_panzer', 'samar_iran', 'uomomees', 'ggehhry2', 'masoudslii', 'irbozorg', 'mostafaa_karimi', 'saiedehsaideh59', 'kambizghafouri', 'mehdihajati', 'jiar06731264', 'd0wn_under', 'golestanparsa', 'barfiiiran', 'iranplateau1', 'a_jafarzadeh', 'aliaghell', 'neda73neda', 'marie36822764', 'mahistan', 'parwaz22', 'mahmoudzibaie', 'sedaye_iran', 'saba_khoi', 'peroz401939762', 'majidh44995071', '0mhp037', 'schahrzad_b', 'mery202120', 'masad75405681', 'khatibiofficial', 'smjm1972', 'rezahashemi1919', 'masioob', 'me_hamed_myself', 'pegah_shirazi', 'havin_n5', 'toukaneyestani', 'faranakazad1', 'naslsokhteh60', 'iran_vdt', 'navidi49', 'green_amir', 'sarbazeh_vatan1', 'frarandeh', 'radman2576', 'young_sheldon1', 'malusakam', 'roshangarnasl', 'navidmajd11', 'alihamid27', '__injaneb96', 'hzarkesh', 'mahdieh_golroo', 'amooamirkhan', 'antiprop_aganda', 'alireza_hafezi1', 'bahar_e_azadi', 'abornaei', '_ashkaval_', 'quietgirl7319', 'jalovemila', 'pahlavikhah43', 'patrick_jane77', 'mahboubeh_mdi', 'satggin', 'shahiavid', 'with_pahlavi3', 'rppress0', 'saramobarez1', 'miss_maropelle', 'silmaethdante', 'dargoldan2', 'nastaran9638495', 'loabatk', 'vahid_esmaeilii', 'soheili84', 'mayekhal', 'mr20228', 'sinatoossi', 'roshanaeii', 'lnahalllnahall', 'darushirani13', 'addison77866447', 'parand____', '2expvzwq7llpx4p', 'hs_maryam', 'memarsadeghi', 'mollah', 'sashtyani', 'hastyarrr', 'daystar98173834', 'aghachurchill', 'drshehabp', 'yarabaydad', 'angel71as', 'azarbayjanx', 'kamalpishvandi', 'farbodahmadi880', 'omid_av2', 'medinfo_x', 'hambastegi', 'twittbirds7', 'bernoam', 'majidazarpey', 'naeimehdoustdar', 'sababagherii', 'mashinmonee', 'shararehtalaeii', 'hekasrehcrisis', 'mazdakbamdadan2', 'iranariyayi64', 'mojtabanikoo', 'koroshcr7', 'mhrdadbarandaz3', 'aplcarolinedr', 'mahnazshirali', 'far_yaddd', 'arianarian00', 'hhellfireeeeee', 'seedhossein2111', 'shaheenchevv', 'mashrotehorg', 'nemo_regnum', 'ali49781135', 'ariamehhr', 'mehr_mihan', 'nasehmohi', 'aazadian2005', 'sfaeze_alavi', 'roobahyab1', 'freedom_of_ir', 'cameronbehzadi', 'rosebuddonkhoan', 'safaidarya', 'soleymaniazadeh', 'azadchakavak', 'freeman010', 'sangtarash_azad', 'pahlavi_yasmine', 'iran_farda1', 'gohareshghi', 'matinkhaledii', '2tosgzcfj8vtsjk', 'shah_parast_k', 'sheykhbabar2', 'jooldooz', 'lishaghayeghli', 'nargesfnd', 'tomasshellllby', 'shdelfan', 'libertyiranian', 'naslesookhtehh', 'javidshah0000', '007mi00', 'dawnandthex', 'leiliii27', 'beevan88', 'persiangw', 'x4lirez4x', 'omidkt62', 'kiarashfarasat1', 'saeid_555555', 'm_ojmal', 'djhastammoho', 'iranzad_98', 'itisbatgirl', 'liberti2022', 'remisgp', 'haniiiissss1387', 'yaldarod', 'mojgan07798961', 'powerpeople_', 'iran22851566', 'amiriysara', 'jc_constantine1', 'ddsbobby', 'tanha59977799', 'santamorte00', 'artemizshahdokh', 'cowboy_datoboy', 'javidaniranema'], 'pseudo_training_user_keys': ['1m1peacefighter', '288_hamid', '46_yazdan', '4womlifefreedom', '76eng76', '7th8fy9tw7', '_leyla_gh', '_oktapos', 'a92753297', 'a_eslammanesh', 'abandukht1', 'abedi_maso63131', 'adavivahid7646', 'afiflysky', 'aghaei198688364', 'ahoramazda271', 'ainazmme', 'ajabreaking', 'ajami_david', 'albiladpress', 'alhadath', 'alimoazzen00', 'alinajibiii', 'alinejadsiyamak', 'alirezapershian', 'alirezasafaria1', 'alkar1899342', 'almayadeenlive', 'amir_mahdipour5', 'amirhossei25524', 'amiry72782', 'amis29881319', 'amper8807214017', 'amydllhi', 'anayata73549426', 'andrew615066', 'angelvibes2024', 'anibah20', 'ankit2290537665', 'ankit_chandola', 'annagha1380', 'anonymous010625', 'anonymousace006', 'anuriera', 'aquarius1964', 'aramsalarjahan', 'arash_shakoori', 'arashpakzad13', 'arenayatzadeh', 'arjangdiv1', 'armex_motarez', 'arsaghasempour', 'arshia_j', 'artan496', 'artemis540721', 'artemisbar80016', 'aryaei_iraniam', 'as197373', 'asharqnews', 'ashofteh_hal', 'asre_bishouri', 'atash6848', 'aynodlady', 'ayubazadi90', 'azadi14650811', 'azadiiinim7642', 'azadinazdikastt', 'azta68014549', 'babak172818', 'babak19700', 'babakmorad92996', 'babakparsa151', 'bachereza', 'bad____robot', 'baghdadisa58670', 'bahram32136719', 'barzinbaba1506', 'bbcnews', 'bbcworld', 'bdn15036475174', 'beeechareh', 'behiariyayi_ffi', 'behnaz28', 'behnoushsoltan2', 'behrouz1831089', 'belendlaura', 'belyad42833', 'beygihome', 'beykzadesoheyl', 'bhkhda29584', 'binnatrauf', 'bl099er101', 'blindassassin06', 'bluedamavand', 'bluewhite2582', 'bn50933945', 'bsdr166', 'bz_melisa', 'carpediemtop', 'cedar315894', 'chatara2001', 'cleophee98', 'd62darya', 'daffodil27', 'daniel043821253', 'dariush96173036', 'dariushkingph', 'dark_nighting_m', 'davar43639076', 'davoodirooni191', 'dehkordiazar', 'demtheiran', 'derafshmedia', 'diidebann', 'djdjs38537152', 'doomsdaycomming', 'dordaneh_irani', 'drmamuoti', 'eairanparast', 'elham1981k', 'elham42302688', 'endless00summer', 'erfxov', 'eric792056', 'esep65', 'estoucomisrael', 'farhad61595028', 'fari71880431', 'farrah72691415', 'farzad777777', 'farzad_1195', 'fatemag21', 'fateme_nrn', 'fereydounfaro', 'ferimilani', 'firedragon243', 'first8pa', 'francisbrian19', 'frbdgrbni', 'freeee86', 'freeexpression8', 'freeiran_forus', 'frhd47', 'fwti_kvn81', 'g_alikin7650', 'getnet_bereket', 'gh0qn00s', 'ghapalinazar', 'gly686155851500', 'godfreedomiran8', 'h2sapiens', 'hamide_jafari1', 'hamidkrg', 'hamidtrade67', 'hani_shafiee_1', 'hannah86872721', 'hasankachal1402', 'hashymashy', 'hbahadorany', 'hd_archi', 'hedil70902045', 'herserenelibre', 'hhaaajjjj', 'hima777_', 'hn977163', 'hollywoodpersia', 'homaioiir', 'horina387787', 'hosein_cfz', 'hossein126nl', 'hossein69481295', 'hz7_matin', 'iironee1', 'imsimplewoman', 'independent', 'ir369yarshah', 'iran_javid2500', 'iran_man88', 'irand0kht', 'iranian_spring', 'iranianpatrio1', 'iranmylove2018', 'iransaz', 'iranzamin2583', 'iranziba1401', 'izak_fouad', 'jasonjan1341', 'javid_rezashah', 'jbl64348', 'jejehdhshs67790', 'jhabiz', 'jilla9', 'jlylh7956', 'kafshdozakkkk', 'kaleshaghe', 'kamyarakba12880', 'kann_news', 'karen_vafai', 'kaveahanga2022', 'kaveh_irann', 'kdhdld25959', 'key_pars', 'keywarzan', 'kheradjooo', 'kianomadi', 'kiki197352', 'kimiing6', 'king12991', 'kingerland', 'kiyanurad', 'komodsaazkiooni', 'krezapahlavi', 'kyarashkyayy', 'laburnum1000', 'lalibertad777', 'langrudi55430', 'ldnif1', 'learningruston', 'lebforcesnews', 'leilariahipanah', 'letsgobrando45', 'lf71354556', 'lfamily16606233', 'lili65876849747', 'loghmanss', 'longliveiran401', 'm_r_a1977', 'madam_franklin', 'madscience2099', 'mah5448226', 'mahdi35711413', 'mahraha99', 'mahshid78364573', 'mahtab_2022', 'majidrezarahna2', 'malekimort21297', 'mallys58560164', 'mamadfreedom9', 'mamanamina83', 'mamanbozork', 'mansoor55759461', 'mariaafshar11', 'marif24145', 'maryam65237865', 'maryam8223262', 'maryama88097336', 'masjoon0220', 'maysamnoorelah1', 'mb_irani', 'mehran05836997', 'mehrdad_s21', 'melani18052417', 'melor28n', 'mene129957', 'meysam_hoosh', 'mia795806987870', 'miinnikaaa', 'miiran20194', 'milad1388226', 'minimalist82028', 'mmasood331448', 'mmdbyt322497', 'mohammadstm1', 'mohtashampoone', 'monadehnad', 'moreza997', 'mozhgan47', 'mr_m_salar', 'mr_naaam', 'msa_gh77', 'msotedlan15136', 'mstfahsini65', 'mtanha03530340', 'mtiwdi51811', 'n60762mhsa', 'naderafsharjam', 'nadrzandi', 'nahidsh527641', 'nasrin63467831', 'newopportuniti', 'ngh2017', 'nickbanoo78', 'nik_mirbat', 'nikoo10452225', 'niya64_', 'noore_shomal', 'nooribaran60419', 'noosebreakers', 'nouri_sepi14264', 'omidirniazad', 'omidkaviani369', 'omidvan', 'online_khabar', 'p36108payam', 'padeshahpahlavi', 'pahlavi0211', 'pahlavist091339', 'pakdelmoien', 'pandaye_skini', 'panifey', 'parham1345', 'parisach52', 'parsemard', 'parvinkonig', 'parya6530', 'persianblood_', 'persiangulf71', 'pesarfokoli', 'peyman458026040', 'peymanhj', 'phoenix347869', 'piroozii6', 'pjr1345', 'prophetwhe93679', 'psychology49590', 'qzhv41111', 'radfarzari', 'rahaey198039194', 'rahaska92', 'rangrazian92291', 'rasookosh', 'razrad1395', 'rda_mhmd32862', 're_z_4', 'real4k2024', 'rendkharabat56', 'reyhanehza7655', 'rina_ghz', 'ro2327128435349', 'rosa78412868', 'rp_ir57', 'rrrs1550246', 'sadeqreza777', 'saira_solmaz', 'salarz242967', 'saleh_hey00', 'samibygi129', 'sarahmicheal47', 'scarface2582', 'seamorgh1', 'senobar20221', 'sepehriran2022', 'shah200382', 'shahdadmahr123', 'shahnamekhan', 'shahrooz78', 'shangolmirza', 'shaporyekom', 'shari32521943', 'sherrygerami', 'sherwin30546', 'sholehroshan', 'shryr594830', 'silicone_14', 'silver_piruz', 'sina_filino', 'sirus1264330', 'siyavash_shooo', 'skynewsarabia_b', 'smianabi', 'sohrab120014852', 'sohrabtec', 'soroushsor90214', 'speed_snail86', 'springforall', 'ss22564940', 'ssubzer00', 'stealthmedical1', 'sunriseinw14362', 'takeback_iran', 'tammnews', 'taranehraki', 'tazehramin', 'tazevareed', 'therealmindman', 'thoseini5439', 'toialerts', 'torj_mosvi', 'unknowntmuser', 'vahidq121212', 'vatanprast59', 'visa_best', 'xbwe5p0sb48vfgp', 'xoyoye2995', 'yasharatighi', 'yatok', 'yourhearse1', 'z3a6i9', 'zakadamoon', 'zohrehfardi'], 'pseudo_draws': 32300, 'initialization': 'pinned_teacher_state', 'checkpoints': {'best_validation_loss': 'models/pseudo_student_best_validation_loss.pt', 'last': 'models/pseudo_student_last.pt'}}

    epoch  labeled_loss  pseudo_loss  validation_loss
0       1      0.601925     0.347626         1.188318
1       2      0.611947     0.137192         1.197538
2       3      0.569986     0.154625         1.213726
3       4      0.562996     0.090815         1.230891
4       5      0.619688     0.120663         1.304592
5       6      0.575527     0.090671         1.280759
6       7      0.543762     0.096064         1.296020
7       8      0.537856     0.095257         1.260869
8       9      0.557357     0.071650         1.228590
9      10      0.551633     0.116406         1.254902
10     11      0.486120     0.066012         1.268036
11     12      0.542685     0.057806         1.273794
12     13      0.512940     0.061339         1.339280
13     14      0.583508     0.063769         1.296341
14     15      0.521213     0.065644         1.366728
15     16      0.536459     0.059994         1.371792
16     17      0.550616     0.064592         1.324089
17     18      0.520816     0.080784         1.281310
18     19      0.496980     0.043429         1.307468
19     20      0.507552     0.042476         1.323971
20     21      0.506413     0.039627         1.342363
21     22      0.488577     0.036421         1.300683
22     23      0.450427     0.064992         1.332775
23     24      0.524466     0.060267         1.381641
24     25      0.446866     0.060236         1.409880
25     26      0.485164     0.042908         1.400036
26     27      0.525706     0.033267         1.398362
27     28      0.529395     0.047282         1.312771
28     29      0.516771     0.057496         1.365569
29     30      0.462934     0.035831         1.428616
30     31      0.448968     0.044945         1.335735
31     32      0.526501     0.044493         1.435445
32     33      0.459133     0.029282         1.437459
33     34      0.404275     0.039259         1.448698
34     35      0.505424     0.034963         1.512941
35     36      0.499291     0.072111         1.553136
36     37      0.488128     0.036039         1.641245
37     38      0.449363     0.019248         1.431415
38     39      0.456803     0.052469         1.477765
39     40      0.461263     0.027526         1.428079
40     41      0.427666     0.047266         1.431442
41     42      0.455609     0.025577         1.400869
42     43      0.480573     0.037385         1.600619
43     44      0.525600     0.018186         1.692928
44     45      0.431040     0.056202         1.589002
45     46      0.388127     0.023478         1.471751
46     47      0.480397     0.024602         1.471453
47     48      0.445650     0.025303         1.670272
48     49      0.429345     0.028118         1.574261
49     50      0.480872     0.013128         1.654116

## Evaluation and training-population comparison

Teacher, labeled-only control, and pseudo student are compared on the identical frozen validation/test populations. This is a same-population continuation comparison; it does not prove causal benefit, calibration, or deployment readiness.

In [6]:
metrics = run.export()
display(metrics)
display(__import__('pandas').read_csv(run.output_dir / 'reports' / 'training_populations.csv'))
display(__import__('pandas').read_csv(run.output_dir / 'reports' / 'supervised_control_student_comparison.csv'))

,model,split,cohort,population_n,evaluated_n,missing_predictions_n,coverage,human_n,bot_n,accuracy,bot_precision,bot_recall,bot_f1,roc_auc,average_precision
0,supervised_teacher,train,all_users,671,671,0,1.0,540,131,0.895678,0.656410,0.977099,0.785276,0.975997,0.891520
1,supervised_teacher,validation,all_users,144,144,0,1.0,116,28,0.701389,0.346939,0.607143,0.441558,0.734606,0.450877
2,supervised_teacher,test,all_users,144,144,0,1.0,116,28,0.708333,0.333333,0.500000,0.400000,0.736453,0.432441
3,labeled_control,train,all_users,671,671,0,1.0,540,131,0.885246,0.632353,0.984733,0.770149,0.981411,0.917951
4,labeled_control,validation,all_users,144,144,0,1.0,116,28,0.729167,0.382979,0.642857,0.480000,0.739840,0.478554
5,labeled_control,test,all_users,144,144,0,1.0,116,28,0.673611,0.268293,0.392857,0.318841,0.731527,0.429183
6,pseudo_student,train,all_users,671,671,0,1.0,540,131,0.822653,0.526786,0.900763,0.664789,0.925770,0.755026
7,pseudo_student,validation,all_users,144,144,0,1.0,116,28,0.680556,0.333333,0.642857,0.439024,0.716133,0.434114
8,pseudo_student,test,all_users,144,144,0,1.0,116,28,0.708333,0.340909,0.535714,0.416667,0.748153,0.440313

,population,human_labeled,pseudo_human,pseudo_bot,validation_labels_in_training,test_labels_in_training
0,supervised_teacher,671,0,0,False,False
1,labeled_control,671,0,0,False,False
2,pseudo_student,671,195,195,False,False

,model,split,comparison_type,cohort,population_n,evaluated_n,missing_predictions_n,coverage,human_n,bot_n,accuracy,bot_precision,bot_recall,bot_f1,roc_auc,average_precision
0,supervised_teacher,validation,same_frozen_population_continuation_control,all_users,144,144,0,1.0,116,28,0.701389,0.346939,0.607143,0.441558,0.734606,0.450877
1,labeled_control,validation,same_frozen_population_continuation_control,all_users,144,144,0,1.0,116,28,0.729167,0.382979,0.642857,0.480000,0.739840,0.478554
2,pseudo_student,validation,same_frozen_population_continuation_control,all_users,144,144,0,1.0,116,28,0.680556,0.333333,0.642857,0.439024,0.716133,0.434114
3,supervised_teacher,test,same_frozen_population_continuation_control,all_users,144,144,0,1.0,116,28,0.708333,0.333333,0.500000,0.400000,0.736453,0.432441
4,labeled_control,test,same_frozen_population_continuation_control,all_users,144,144,0,1.0,116,28,0.673611,0.268293,0.392857,0.318841,0.731527,0.429183
5,pseudo_student,test,same_frozen_population_continuation_control,all_users,144,144,0,1.0,116,28,0.708333,0.340909,0.535714,0.416667,0.748153,0.440313

## Verification and downstream limits

Verification checks artifact hashes, the full pseudo-label pool, deterministic class-balanced selection, identity disjointness, teacher compatibility, saved checkpoints, keyed predictions and evaluation reports. The student and control checkpoints are distinct from the supervised teacher. A description-based or missing-modality multimodal semi-supervised method requires a separate experiment.

In [7]:
verification = verify_run(ROOT, run.output_dir)
print(run.output_dir)
display(verification)

C:\Users\p.vazifeh\Desktop\University\Project\Bot Detection Implementation\results\versions\semi_supervised_v2\20260920T104058299599Z_da452759

{'verified_artifacts': 34,
 'full_pseudo_pool': 18331,
 'selected_pseudo': 390,
 'selected_distribution': {0: 195, 1: 195},
 'reloaded_checkpoints': 4,
 'verified_prediction_files': 9,
 'verified_metric_rows': 9}